100-hours-a-week/6-nemo-be

build.gradle.kts
src/main/resources/application.yml

→ Spring Boot Actuator의 /actuator/health 엔드포인트를 활성화했습니다.
→ 배포 후 롤백 트리거용으로 헬스 체크가 필요하며, 모니터링 시스템과의 통합을 위한 최소 구성입니다.
→ spring-boot-starter-actuator 의존성 추가
→ application.yml에 management.endpoints.web.exposure.include=health 설정 추가
→ management.endpoint.health.show-details=never 설정으로 세부 정보 노출 방지

feat: add basic actuator health check endpoint for monitoring

---

.github/workflows/dev-cd.yaml
.github/workflows/dev-ci.yaml
.github/workflows/pr-ci.yaml
build.gradle.kts
deploy/deploy.sh
deploy/rollback.sh
deploy/validate.sh
src/main/java/kr/ai/nemo/auth/controller/AuthController.java
src/main/java/kr/ai/nemo/auth/controller/OauthController.java
src/main/java/kr/ai/nemo/auth/domain/UserToken.java
src/main/java/kr/ai/nemo/auth/domain/enums/DefaultUserValue.java
src/main/java/kr/ai/nemo/auth/domain/enums/LoginDevice.java
src/main/java/kr/ai/nemo/auth/domain/enums/OAuthProvider.java
src/main/java/kr/ai/nemo/auth/dto/KakaoTokenResponse.java
src/main/java/kr/ai/nemo/auth/dto/KakaoUserResponse.java
src/main/java/kr/ai/nemo/auth/exception/OAuthErrorCode.java
src/main/java/kr/ai/nemo/auth/exception/OAuthException.java
src/main/java/kr/ai/nemo/auth/jwt/JwtProvider.java
src/main/java/kr/ai/nemo/auth/repository/UserTokenRepository.java
src/main/java/kr/ai/nemo/auth/service/OauthService.java
src/main/java/kr/ai/nemo/auth/service/UserTokenService.java
src/main/java/kr/ai/nemo/common/exception/ApiResponse.java
src/main/java/kr/ai/nemo/common/exception/GlobalExceptionHandler.java
src/main/java/kr/ai/nemo/config/AppConfig.java
src/main/java/kr/ai/nemo/user/domain/User.java
src/main/java/kr/ai/nemo/user/domain/enums/UserStatus.java
src/main/java/kr/ai/nemo/user/dto/UserDto.java
src/main/java/kr/ai/nemo/user/dto/UserLoginResponse.java
src/main/java/kr/ai/nemo/user/repository/UserRepository.java
src/main/resources/application.yml

→ 카카오 간편 로그인 API 개발하였습니다.
→ 사용자가 쉽고 빠르게 서비스에 회원가입/로그인을 할 수 있습니다.
→ OauthController에 카카오 콜백 엔드포인트 추가
→ OauthService에서 카카오 인가 코드로 사용자 정보 조회 및 JWT 발급 처리
→ User 테이블에 provider, providerId 기반 사용자 저장 로직 추가
→ 에러 발생 시 OAuthException 및 OAuthErrorCode를 통한 예외처리 적용
→ 기본값 및 로그인 디바이스/프로바이더 관련 Enum 분리
→ closed #19

Merge: featue/user-login-kakao

---

src/main/java/kr/ai/nemo/config/SecurityConfig.java
src/main/java/kr/ai/nemo/group/participants/controller/GroupParticipantsController.java
src/main/java/kr/ai/nemo/group/participants/domain/GroupParticipants.java
src/main/java/kr/ai/nemo/group/participants/dto/GroupParticipantDto.java
src/main/java/kr/ai/nemo/group/participants/dto/GroupParticipantsListResponse.java
src/main/java/kr/ai/nemo/group/participants/repository/GroupParticipantsRepository.java
src/main/java/kr/ai/nemo/group/participants/service/GroupParticipantsService.java
src/main/java/kr/ai/nemo/group/service/GroupCommandService.java
src/main/java/kr/ai/nemo/group/service/GroupQueryService.java

→ 모임 ID 기준 모임원 조회 API를 구현했습니다.
→ 모임 상세 페이지에서 현재 참여 중인 멤버 목록을 보여주기 위해 필요했습니다.
→ GET /api/v1/groups/{groupId}/participants 엔드포인트 추가
→ GroupParticipantsService에 getAcceptedParticipants 메서드 구현
→ 참여 상태가 JOINED인 사용자만 필터링하여 반환
→ 응답 DTO: GroupParticipantDto, GroupParticipantsListResponse 정의
#29 #31

feat: 그룹 ID로 모임원 목록 조회 API 개발 (JOINED 상태 기준)

---

src/main/java/kr/ai/nemo/config/SecurityConfig.java
src/main/java/kr/ai/nemo/group/participants/controller/GroupParticipantsController.java
src/main/java/kr/ai/nemo/group/participants/dto/MyGroupDto.java
src/main/java/kr/ai/nemo/group/participants/dto/MyGroupListResponse.java
src/main/java/kr/ai/nemo/group/participants/repository/GroupParticipantsRepository.java
src/main/java/kr/ai/nemo/group/participants/service/GroupParticipantsService.java

→ 나의 모임 list 조회 API를 구현했습니다.
→ 사용자가 본인이 참여 중인 모임을 확인할 수 있도록 하기 위함입니다.
→ GET /api/v1/groups/me API 엔드포인트 추가
→ GroupParticipantsService에 getMyGroups(userId) 로직 추가
→ MyGroupDto, MyGroupListResponse DTO 설계 및 적용
→ Security 설정에서 /groups/me 경로는 인증 필요하도록 수정
#29 #30

feat: 나의 모임 list 조회 API 구현

---

src/main/java/kr/ai/nemo/common/exception/ResponseCode.java
src/main/java/kr/ai/nemo/schedule/controller/ScheduleController.java
src/main/java/kr/ai/nemo/schedule/service/ScheduleCommandService.java

→ 일정을 취소하는 API 개발 완료하였습니다.
→ 일정 생성자는 일정을 자유롭게 취소할 수 있습니다.
→ DELETE /api/v1/schedules/{scheduleId}
→ 일정 생성자만 삭제할 수 있으므로 error 메세지 추가하였습니다.
→ delete_at 이 추가되며, 상태값이 CANCELED로 변경되도록 합니다.

feat: 일정 삭제(취소) API 개발

---

src/main/java/kr/ai/nemo/schedule/controller/ScheduleController.java
src/main/java/kr/ai/nemo/schedule/dto/ScheduleDetailResponse.java
src/main/java/kr/ai/nemo/schedule/participants/domain/ScheduleParticipant.java
src/main/java/kr/ai/nemo/schedule/participants/domain/enums/ScheduleParticipantStatus.java
src/main/java/kr/ai/nemo/schedule/participants/repository/ScheduleParticipantRepository.java
src/main/java/kr/ai/nemo/schedule/service/ScheduleCommandService.java
src/main/java/kr/ai/nemo/schedule/service/ScheduleQueryService.java

→ 일정 상세를 조회하는 API 개발 완료하였습니다.
→ 사용자는 일정의 상세 내용을 조회할 수 있습니다.
→ 일정 상세 내용을 조회할 수 있도록 service, comtroller, repository를 추가하였습니다.
→ 누구나 조회할 수 있기 때문에 SecurityConfig 추가하였습니다.
→ 일정 참여자 조회를 위해 일정 참여자 domain을 추가하였습니다.
> #36 #37 #39

feat: 일정 상세 조회 API 개발 (#38)

---

src/main/java/kr/ai/nemo/config/SecurityConfig.java
src/main/java/kr/ai/nemo/group/controller/GroupController.java
src/main/java/kr/ai/nemo/group/dto/GroupListResponse.java
src/main/java/kr/ai/nemo/group/service/GroupQueryService.java
src/main/java/kr/ai/nemo/schedule/controller/ScheduleController.java
src/main/java/kr/ai/nemo/schedule/dto/PageRequestDto.java
src/main/java/kr/ai/nemo/schedule/dto/ScheduleListResponse.java
src/main/java/kr/ai/nemo/schedule/repository/ScheduleRepository.java
src/main/java/kr/ai/nemo/schedule/service/ScheduleQueryService.java

→ 모임의 일정 list를 조회하는 API 개발 완료하였습니다.
→ 모임별 어떤 일정이 있었는지, 어떤 일정들이 있는지 확인할 수 있습니다.
→ Get /api/v1/group/{groupId}/schedules API 개발하였습니다.
→ 누구나 조회가 가능하므로 SecurityConfig 재확인 하였습니다.
→ Group 도메인 내 Controller 에 GetMapping 추가하였습니다.

feat: 모임 일정 list 조회 API 개발

---

src/main/java/kr/ai/nemo/common/exception/ResponseCode.java
src/main/java/kr/ai/nemo/group/domain/Group.java
src/main/java/kr/ai/nemo/group/participants/domain/enums/Status.java
src/main/java/kr/ai/nemo/group/participants/service/GroupParticipantsService.java
src/main/java/kr/ai/nemo/schedule/controller/ScheduleController.java
src/main/java/kr/ai/nemo/schedule/participants/controller/ScheduleParticipantsController.java
src/main/java/kr/ai/nemo/schedule/participants/domain/ScheduleParticipant.java
src/main/java/kr/ai/nemo/schedule/participants/domain/enums/ScheduleParticipantStatus.java
src/main/java/kr/ai/nemo/schedule/participants/dto/ScheduleParticipantDecisionRequest.java
src/main/java/kr/ai/nemo/schedule/participants/repository/ScheduleParticipantRepository.java
src/main/java/kr/ai/nemo/schedule/participants/service/ScheduleParticipantsService.java
src/main/java/kr/ai/nemo/schedule/repository/ScheduleRepository.java
src/main/java/kr/ai/nemo/schedule/service/ScheduleCommandService.java

→ 사용자가 일정 참석/거절을 응답하는 API 개발 완료하였습니다.
→ 사용자가 일정을 참석할지 거절할지 결정할 수 있습니다,
→ 다른 사람들은 일정에 누가 참여하는지 알 수 있습니다.
→ Controller 내 API 로직 추가하였습니다.
→ Service 내 일정 참여자의 상태값을 바꾸는 setter를 추가하였습니다.
→ Repository에서 이미 응답한 경우에는 다시 선택할 수 없도록 하였습니다.

feat: 일정 참석/거절 API 개발 완료 (#48)

---

src/main/java/kr/ai/nemo/schedule/controller/ScheduleController.java
src/main/java/kr/ai/nemo/schedule/dto/MySchedulesResponse.java
src/main/java/kr/ai/nemo/schedule/participants/domain/enums/ScheduleParticipantStatus.java
src/main/java/kr/ai/nemo/schedule/participants/repository/ScheduleParticipantRepository.java
src/main/java/kr/ai/nemo/schedule/service/ScheduleQueryService.java

→ 나의 일정(참여 전·참여 중·완료) 목록을 한 번에 조회하는 API를 개발 완료하였습니다.
→ 사용자가 일정을 하나의 화면에서 전환하며 볼 수 있도록 하기 위함입니다.
→ ScheduleParticipant 기반으로 참여 상태별 일정 분류 로직 추가
→ 참여 상태에 따른 응답 DTO 구조 정의 및 매핑
→ ScheduleParticipantsService, ScheduleQueryService에 비즈니스 로직 분산 처리
→ #48

feat: 나의 일정 목록 조회 API 구현 (#49)

---

src/main/java/kr/ai/nemo/config/SchedulerConfig.java
src/main/java/kr/ai/nemo/schedule/domain/Schedule.java
src/main/java/kr/ai/nemo/schedule/repository/ScheduleRepository.java
src/main/java/kr/ai/nemo/scheduler/ScheduleStatusUpdater.java
src/main/resources/application.yml

→ Spring Scheduler를 사용하여 5분마다 일정 상태를 검사하는 기능을 구현하였습니다.
→ 시작시간이 된 일정은 완료처리가 되어 더이상 신청할 수 없도록 합니다.
→ scheduler 패키지가 추가되었습니다.
→ config 파일이 추가 되었습니다.

feat: 일정 완료 자동 처리 구현 (#53)

---

src/main/java/kr/ai/nemo/group/participants/dto/GroupParticipantDto.java
src/main/java/kr/ai/nemo/group/participants/service/GroupParticipantsService.java
src/main/java/kr/ai/nemo/schedule/repository/ScheduleRepository.java
src/main/java/kr/ai/nemo/schedule/service/ScheduleQueryService.java

→ 모임원 list 반환시 role (MEMBER, LEADER) 상태값을 함께 반환하도록 하였습니다.
→ 취소된 일정은 모임별 일정 list 조회시 제외되도록 하였습니다.
→ UX 측면을 고려하여 추가하였습니다.
→ 모임원 list 반환 DTO의 인자를 User에서 Participants 로 변경하였습니다.
→ JPA 에 StatusNot 쿼리를 추가하였습니다.

feat: 응답 body 변경

---

src/main/java/kr/ai/nemo/config/CorsConfig.java

→ https:// 네모 도메인의 CORS를 허용합니다.
→ 도메인에서 접근할 수 있습니다.
→CorsConfig 파일 수정하였습니다.

feat: 도메인 CORS 허용

---

src/main/java/kr/ai/nemo/schedule/dto/ScheduleDetailResponse.java

→ 일정 참여자 상세 조회시 출력되는 일정 참여자 list 의 body값을 변경합니다.
→ UI적인 측면을 고려하였습니다.
→ 일정 상세 조회시 일정을 만든 사용자의 ID값이 아닌, nickname이 출력되도록 합니다.
→ 일정 참여자 list 조회시 모임의 maxUserCount값을 추가하였습ㄴ다.

feat: 일정 상세 조회 시 response body 변경

---

src/main/java/kr/ai/nemo/auth/controller/OauthController.java
src/main/java/kr/ai/nemo/auth/service/OauthService.java
src/main/java/kr/ai/nemo/group/controller/GroupController.java
src/main/java/kr/ai/nemo/schedule/controller/ScheduleController.java
src/main/java/kr/ai/nemo/schedule/dto/PageRequestDto.java
src/main/java/kr/ai/nemo/schedule/dto/ScheduleDetailResponse.java
src/main/java/kr/ai/nemo/user/dto/UserDto.java
src/main/java/kr/ai/nemo/user/dto/UserLoginResponse.java

→ refresh token 방식 변경
→ 일정 상세 조회 시 status 값 추가
→ refresh token을 body에 보낼 시 XSS 공격에 취약함.
→ 일정 상세 조회 시 status 값으로 현재 일정 상태를 확인할 수 있음.
→ body에서 제외하고, Cookie로 저장하도록 변경

feat: refresh token 방식 변경 / 일정 상세 조회 시 status 값 추가

---

src/main/java/kr/ai/nemo/group/service/GroupCommandService.java
src/main/java/kr/ai/nemo/image/service/ImageService.java
src/main/resources/application.yml

→ 모임 관련 사진을 S3에 저장하도록 합니다.
→ 모임 생성시 대표 사진을 S3에 등록하여 이미지 url을 유지합니다.
→ image Service 내 group으로 들어가는 logic 추가
→ #77

feat: 모임 사진 S3에 저장하는 logic 구현

---

src/main/java/kr/ai/nemo/auth/controller/OauthController.java
src/main/java/kr/ai/nemo/auth/service/OauthService.java
src/main/java/kr/ai/nemo/common/UriGenerator.java

→ access token 반환 방식 변경 완료하였습니다.
→ OAuth2 로그인 시 302 redirect로 body를 반환할 수 없기 때문에 파라미터로 전달되도록 하였습니다.
→ URI 수정
→ #77

feat: access token 반환 방식 변경 (#79)

---

src/main/java/kr/ai/nemo/auth/controller/OauthController.java
src/main/java/kr/ai/nemo/common/UriGenerator.java
src/main/java/kr/ai/nemo/config/SecurityConfig.java

→ OAuth 로그인 플로우를 수정합니다.
→ 기존에는 카카오 로그인 이후 리디렉션되는 URI가 고정되어 있어,
→ 프론트엔드 로컬 환경에서 테스트가 어렵고
→ 인스턴스마다 환경변수를 설정해야 하는 불편함이 있었습니다.
→ 프론트엔드가 백엔드의 로그인 API(`/api/v1/login/kakao`)에 `redirect_uri` 파라미터를 포함하여 요청
→ 백엔드는 해당 redirect URI를 OAuth `state` 파라미터로 포함해 카카오 인증 페이지로 리디렉션
→ 인증 완료 후, 백엔드는 전달받은 `state` 값을 기반으로 최종 redirect 처리 및 토큰 전달
→ Closes #84

feat: oauth 동작 방식 변경 (#84)

---

src/main/java/kr/ai/nemo/group/repository/GroupRepository.java
src/main/java/kr/ai/nemo/group/service/GroupQueryService.java

→ 모임 list 출력 시 해체된 모임도 출력되는 에러 수정
→ 해체된 모임을 사용자에게 출력하면 혼란을 야기할 수 있습니다.
→ JPA Query를 수정하였습니다.

fix: 해체된 모임은 list 조회 불가

---

.github/workflows/cd-v1-prod.yaml
.github/workflows/ci-v1-prod.yaml
.github/workflows/cicd-v1-dev.yaml

운영(prod) 환경 전용 CI/CD 워크플로우를 개발용 워크플로우와 분리하여 추가하였습니다.
- `ci-prod.yaml`  
- main 브랜치 푸시 시 자동 빌드 및 운영 서버로 JAR 업로드
- `cd-prod.yaml`  
- GitHub Actions → workflow_dispatch → 수동 승인 후 배포 스크립트 실행
- 운영 배포는 수동 승인이 필요한 플로우로 구분되어야 하며, main 브랜치 기준으로 분기되므로 dev 환경과 분리
- 실수로 운영 배포가 자동 실행되는 것을 방지하기 위함
- `.github/workflows/ci-prod.yaml` 추가
- `.github/workflows/cd-prod.yaml` 추가
> 참고 내용을 적습니다.
- 다음 시크릿이 GitHub에 등록
- `PROD_SSH_KEY`
- `PROD_USER`
- `PROD_HOST`
- 운영 서버 내 경로: `~/nemo/backend/jar-backups/`, `~/nemo/backend/scripts/deploy_ci_cd.sh` 필요

infra: 운영 서버용 CI/CD 워크플로우 분리 및 추가

---

src/main/java/kr/ai/nemo/domain/auth/controller/AuthController.java
src/main/java/kr/ai/nemo/domain/auth/service/OauthService.java
src/main/java/kr/ai/nemo/domain/group/controller/GroupController.java
src/main/java/kr/ai/nemo/domain/group/repository/GroupRepository.java
src/main/java/kr/ai/nemo/domain/group/repository/GroupTagRepository.java
src/main/java/kr/ai/nemo/domain/group/service/GroupQueryService.java
src/main/java/kr/ai/nemo/domain/groupparticipants/service/GroupParticipantsQueryService.java
src/main/java/kr/ai/nemo/domain/schedule/service/ScheduleQueryService.java
src/main/java/kr/ai/nemo/domain/scheduleparticipants/repository/ScheduleParticipantRepository.java

→ service 내 DB에 접근하는 모든 logic에 transactional을 적용하였습니다.
→ DB를 조회하는 logic에는 readOnly=true를 적용하였습니다.
→ 조회하는 API 내 DB 조회 쿼리를 JPA가 하는 것이 아닌, 직접 작성하여 N+1 문제를 개선하였습니다.
→ N+1 문제로 CPU가 튀어 서버가 다운되는 현상이 발생하였고, 이 문제를 줄이기 위해 개선하였습니다.
→ service 로직에 transactional을 적용하고, N+1 문제를 개선하여 API 성능을 개선하였습니다.
→ #114 #115

transactional 적용 및 DB 쿼리 개선

---

src/main/java/kr/ai/nemo/domain/group/domain/Group.java
src/main/java/kr/ai/nemo/domain/group/exception/GroupErrorCode.java
src/main/java/kr/ai/nemo/domain/group/repository/GroupRepository.java
src/main/java/kr/ai/nemo/domain/group/validator/GroupValidator.java
src/main/java/kr/ai/nemo/domain/groupparticipants/controller/v1/GroupParticipantsController.java
src/main/java/kr/ai/nemo/domain/groupparticipants/controller/v2/GroupParticipantsController.java
src/main/java/kr/ai/nemo/domain/groupparticipants/domain/GroupParticipants.java
src/main/java/kr/ai/nemo/domain/groupparticipants/domain/enums/Role.java
src/main/java/kr/ai/nemo/domain/groupparticipants/exception/GroupParticipantErrorCode.java
src/main/java/kr/ai/nemo/domain/groupparticipants/repository/GroupParticipantsRepository.java
src/main/java/kr/ai/nemo/domain/groupparticipants/service/GroupParticipantsCommandService.java
src/main/java/kr/ai/nemo/domain/groupparticipants/validator/GroupParticipantValidator.java
src/test/java/kr/ai/nemo/domain/groupparticipants/controller/GroupParticipantsControllerTest.java
src/test/java/kr/ai/nemo/domain/groupparticipants/controller/v1/GroupParticipantsControllerTest.java
src/test/java/kr/ai/nemo/domain/groupparticipants/controller/v2/GroupParticipantsControllerTest.java
src/test/java/kr/ai/nemo/domain/groupparticipants/repository/GroupParticipantsRepositoryTest.java
src/test/java/kr/ai/nemo/domain/groupparticipants/service/GroupParticipantsCommandServiceTest.java

→ 모임원 추방 API를 구현하였습니다.
→ 모임 탈퇴 API를 구현하였습니다.
→ 모임을 더 잘 관리하고, 자유롭게 탈퇴할 수 있도록 하기 위함입니다.
→ 모임원 도메인 내 controller와 service 로직을 추가하였습니다.
→ 단위 테스트 코드 작성하였습니다.
→ #131

모임원 추방, 모임 탈퇴 API 구현

---

src/main/java/kr/ai/nemo/domain/group/controller/v1/GroupController.java
src/main/java/kr/ai/nemo/domain/group/controller/v2/GroupController.java
src/main/java/kr/ai/nemo/domain/group/domain/Group.java
src/main/java/kr/ai/nemo/domain/group/dto/request/UpdateGroupImageRequest.java
src/main/java/kr/ai/nemo/domain/group/exception/GroupErrorCode.java
src/main/java/kr/ai/nemo/domain/group/service/GroupCommandService.java
src/main/java/kr/ai/nemo/domain/group/validator/GroupValidator.java
src/main/java/kr/ai/nemo/infra/ImageService.java
src/test/java/kr/ai/nemo/domain/group/controller/v1/GroupControllerTest.java
src/test/java/kr/ai/nemo/domain/group/controller/v2/GroupControllerTest.java
src/test/java/kr/ai/nemo/domain/group/service/GroupCommandServiceTest.java

→ 모임 대표 사진 수정 API를 개발합니다.
→ 모임 해체 API를 개발합니다.
→ 모임을 나타내는 대표 사진을 수정할 수 있습니다.
→ 모임을 해체할 수 있도록 합니다.
→ S3에 이미지를 업데이트 하면, 기존 이미지는 삭제되도록 합니다.
→ 모임을 해체하면 상태값을 변경합니다.
→ #130

모임 대표 사진 수정, 모임 해체 API

---

src/main/java/kr/ai/nemo/aop/role/aspect/GroupParticipantAspect.java

→ Security Context에서 userDetails를 뽑도록 변경하였습니다.
→ 기존 Long을 뽑도록 하였는데, 그 과정에서 type이 맞지 않아 오류가 발생했습니다.
→ AOP에서 사용하고 있던 (Long) 을 (userDetails)로 변경하였습니다.
→ #139

fix: Security Context에서 userDetails를 뽑도록 변경 (#139)

---

src/main/java/kr/ai/nemo/domain/schedule/validator/ScheduleValidator.java
src/main/java/kr/ai/nemo/domain/scheduleparticipants/service/ScheduleParticipantsService.java

→ 일정 참석 여부를 처음 결정할 때 거절을 하면 상태값 변경이 되지 않는 오류를 수정합니다.
→ 해당 에러는 서비스 운영에 있어 사용자의 정보가 저장이 되지 않는 크리티컬한 에러이므로 hotfix로 해결하였습니다.
→ service 로직 내 조건문을 추가하여 일정 참석 여부 결정 전인 PENDING 상태에서 거절하여도 사용자의 상태값이 변경될 수 있도록 합니다.
→ #145

hotfix: 일정 참석 거절 시 처리 안 되는 오류 해결 (#145)

---

src/main/java/kr/ai/nemo/domain/group/repository/GroupRepository.java

→ 모임 상세 조회가 되지 않는 오류를 해결합니다.
→ JPA가 모임을 여러 개 조회하여 상세 조회가 되지 않는 크리티컬한 문제가 발생했습니다.
→ repository 내의 Query문을 수정하였습니다.

fix: 모임 상세 조회 문제 해결

---

.github/workflows/v2-dev-cicd.yaml

- 백엔드 CI/CD 워크플로우에서 Gradle 빌드 시 캐싱 이슈로 인해 변경사항이 반영되지 않는 문제를 방지하기 위해 Clean Build를 적용하였습니다.
- GitHub Actions에서 캐싱된 *.jar 파일이 그대로 Docker 이미지에 포함되어, 코드 변경 사항이 반영되지 않는 문제가 발생했습니다. 이를 방지하기 위해 ./gradlew clean build를 통해 항상 최신 jar로 빌드하도록 수정했습니다.
- GitHub Actions 워크플로우에서 ./gradlew build → ./gradlew clean build -x test로 변경

Infra: Clean Build로 변경

---

Dockerfile
src/main/resources/application.yml

→ OTLP endpoint 포트 설정 오류 수정 및 application.yml 구성 반영
→기존에 OTLP endpoint를 4317 포트로 설정하여 OpenTelemetry trace export가 실패함.  
Spring Boot Actuator와 OTLP exporter는 기본적으로 HTTP/1.1을 사용하며, 이는 4318 포트를 통해 수신되어야 하므로 수정 필요.
→OTLP export 관련 설정 전체 점검 및 누락된 항목 보완  
→

Fix: OTLP 포트 설정 오류 설정 (4317->4318)

---

build.gradle.kts
src/main/java/kr/ai/nemo/domain/group/domain/enums/AiMessageType.java
src/main/java/kr/ai/nemo/domain/group/dto/websocket/request/GroupRecommendQuestionRequest.java
src/main/java/kr/ai/nemo/domain/group/dto/websocket/request/GroupRecommendRequest.java
src/main/java/kr/ai/nemo/domain/group/dto/websocket/response/GroupRecommendGroupIdResponse.java
src/main/java/kr/ai/nemo/domain/group/dto/websocket/response/GroupRecommendOptionResponse.java
src/main/java/kr/ai/nemo/domain/group/dto/websocket/response/GroupRecommendQuestionResponse.java
src/main/java/kr/ai/nemo/domain/group/dto/websocket/response/GroupRecommendReasonResponse.java
src/main/java/kr/ai/nemo/domain/group/repository/GroupRepository.java
src/main/java/kr/ai/nemo/domain/group/service/GroupCacheKeyUtil.java
src/main/java/kr/ai/nemo/domain/group/service/GroupCacheService.java
src/main/java/kr/ai/nemo/domain/group/service/GroupCommandService.java
src/main/java/kr/ai/nemo/domain/group/service/GroupQueryService.java
src/main/java/kr/ai/nemo/domain/group/service/GroupWebsocketService.java
src/main/java/kr/ai/nemo/domain/groupparticipants/service/GroupParticipantsCommandService.java

→ BE - AI 사이에 WebClient에서 WebSocket으로 변경합니다.
→ 모임 list 조회 시 무효화가 이루어지지 않아서 잘못된 값이 캐싱되는 문제를 해결합니다.
→ 챗봇에 진입 시 사용자에게 처음으로 보여지는 액션을 줄이기 위해 AI에게 Chuck 단위로 텍스트를 전달받습니다.
→ 모임을 수정하거나 삭제해도 모임 list에는 반영이 되지 않는 문제를 해결하기 위함입니다.
→ 기존 사용하고 있던 WebClient를 사용하지 않습니다. (추후 WebSocket이 안정화되면 해당 logic들은 제거할 예정입니다.)
→ cache 키를 별도의 service에서 관리하여 여러 군데 분산되어있는 key를 모읍니다.
→ #191 #192

websocket 도입, 캐싱 문제 해결

---

Dockerfile

- JVM 메트릭이 SigNoz에 수집되지 않던 문제를 해결하기 위해 Java Agent 설정을 수정했습니다.
-기존에는 OTLP HTTP 포트(4318)를 사용하는 설정이었지만, Java Agent는 기본적으로 gRPC 방식(4317)을 사용해야 하며, HTTP 전송 시 metrics endpoint가 Collector에서 404 오류를 반환하고 있었습니다.
- Dockerfile ENTRYPOINT 수정:
- `-Dotel.exporter.otlp.endpoint=http://35.216.67.116:4317` 로 변경
- `-Dotel.exporter.otlp.protocol=grpc` 로 변경
- `application.yml`은 변경 없음 (Spring Actuator 기반 metrics/traces는 그대로 작동하므로)
→https://github.com/100-hours-a-week/6-nemo-be/issues/179#issue-3175466768

Fix: use gRPC (4317) for JVM metric export to Signoz 

---

Dockerfile

→ GC 메트릭 수집을 위해 Dokcer file 수정 
→기존 설정에서는 Signoz에 `jvm.gc.pause` 등의 GC 관련 지표가 수집되지 않아, JVM GC 관련 모니터링이 불가능했습니다.
→ `otel.instrumentation.jvm-metrics.enabled=true` 옵션 추가
→https://github.com/100-hours-a-week/6-nemo-be/issues/179#issue-3175466768

Fix: enable JVM GC Metric in Dockerfile 

---

.github/workflows/v2-prod-cicd.yaml
src/main/java/kr/ai/nemo/domain/auth/controller/AuthController.java
src/main/java/kr/ai/nemo/domain/auth/service/TokenManager.java
src/main/java/kr/ai/nemo/domain/group/service/GroupQueryService.java
src/main/java/kr/ai/nemo/domain/group/service/GroupWebsocketService.java
src/main/java/kr/ai/nemo/domain/groupparticipants/service/GroupParticipantsCommandService.java
src/main/java/kr/ai/nemo/global/config/CorsConfig.java
src/main/java/kr/ai/nemo/global/util/AuthConstants.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml
src/test/java/TokenGenerator.java

→ application을 local, dev, prod를 따로 관리합니다.
→ 캐싱으로 인한 문제를 해결합니다.
→ https로 들어오는 cors를 허용합니다.
→ list가 캐싱되어 페이지가 넘어가도 중복되는 모임 list가 출력되는 오류를 해결합니다.
→ AT 검증을 쿠키로 변경함에 따라 FE 가 local에서 테스트할 수 있도록 cors를 허용합니다.
→ application.yml 관리의 필요성을 느껴 분리하였습니다.
→ 캐싱 무효화 파일 분리, 키 값 별도 파일 관리
→ cors에 htttps://localhost:3000 추가
→ application.yml 파일 분리
→ #200

hotfix/cors 문제, 캐싱 문제 해결
